version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: widen
  ignore:
      # is esm-only
      - dependency-name: chalk
        versions: '>= 5'